# Generated by Django 4.1.13 on 2024-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('reclassification', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=60)),
                ('operator', models.CharField(max_length=20)),
                ('localization', models.JSONField()),
                ('type_of_well', models.JSONField()),
                ('map_datas', models.JSONField()),
                ('dates', models.JSONField()),
            ],
            options={
                'verbose_name': 'Well',
                'verbose_name_plural': 'Wells ',
            },
        ),
    ]
